spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    show-sql: ${SQL_SHOW:true}
    properties:
      hibernate:
        format_sql: ${SQL_FORMAT:true}
    open-in-view: false

  lifecycle:
    timeout-per-shutdown-phase: 30s

  servlet:
    multipart:
      max-file-size: 10MB

  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          starttls:
            enable: true
            required: true

aladin:
  api-key: ${ALADIN_API_KEY}

jwt:
  secret-key: ${JWT_SECRET_KEY:he436dhh$^JhYHRHh5379p8t5ry655%U&^KJ%JU%U$}
  access_exp: ${JWT_ACCESS_EXP:7200}
  refresh_exp: ${JWT_REFRESH_EXP:86400}

cloud:
  aws:
    s3:
      prefix: ${AWS_S3_PREFIX:/}
      bucket: ${AWS_S3_BUCKET:gbook-bucket/}
      base-image-url: ${AWS_S3_URL:/}
    region:
      static: ${AWS_S3_REGION:ap-northeast-2}
    stack:
      auto: false
    credentials:
      access-key: ${AWS_S3_ACCESS}
      secret-key: ${AWS_S3_SECRET}